package com.perisic.smile.login;

import com.perisic.smile.peripherals.GameGUI;

public class Menu extends javax.swing.JFrame{

	/*public void displayScore(String Username){
    usernameLbl.setText(Username);
}*/

public Menu() {
    initComponents();
}

/**
 * This method is called from within the constructor to initialize the form.
 * WARNING: Do NOT modify this code. The content of this method is always
 * regenerated by the Form Editor.
 */
@SuppressWarnings("unchecked")
// <editor-fold defaultstate="collapsed" desc="Generated Code">                          
private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    jLabel3 = new javax.swing.JLabel();
    signoutBt = new javax.swing.JButton();
    usernameLbl = new javax.swing.JLabel();
    playBt = new javax.swing.JButton();
    scoreBt = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jPanel1.setBackground(new java.awt.Color(33, 54, 101));

    jLabel3.setFont(new java.awt.Font("Tahoma", 1, 60)); // NOI18N
    jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Desktop\\CIS\\styles\\blue2.png")); // NOI18N

    signoutBt.setBackground(new java.awt.Color(156, 37, 77));
    signoutBt.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
    signoutBt.setText("Sign Out");
    signoutBt.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            signoutBtMouseClicked(evt);
        }
        public void mousePressed(java.awt.event.MouseEvent evt) {
            signoutBtMousePressed(evt);
        }
    });
    signoutBt.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            signoutBtActionPerformed(evt);
        }
    });

    usernameLbl.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
    usernameLbl.setForeground(new java.awt.Color(67, 168, 223));
    usernameLbl.addComponentListener(new java.awt.event.ComponentAdapter() {
        public void componentShown(java.awt.event.ComponentEvent evt) {
            usernameLblComponentShown(evt);
        }
    });

    playBt.setBackground(new java.awt.Color(67, 154, 151));
    playBt.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
    playBt.setForeground(new java.awt.Color(33, 54, 101));
    playBt.setText("Play");
    playBt.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            playBtMouseClicked(evt);
        }
        public void mousePressed(java.awt.event.MouseEvent evt) {
            playBtMousePressed(evt);
        }
    });
    playBt.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            playBtActionPerformed(evt);
        }
    });

    scoreBt.setBackground(new java.awt.Color(67, 168, 223));
    scoreBt.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
    scoreBt.setForeground(new java.awt.Color(33, 54, 101));
    scoreBt.setText("High Score");
    scoreBt.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mousePressed(java.awt.event.MouseEvent evt) {
            scoreBtMousePressed(evt);
        }
    });
    scoreBt.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            scoreBtActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(52, 52, 52)
                    .addComponent(signoutBt)
                    .addGap(18, 18, 18)
                    .addComponent(usernameLbl))
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(183, 183, 183)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel3)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(playBt, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(scoreBt)))))
            .addContainerGap(196, Short.MAX_VALUE))
    );
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(playBt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(scoreBt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(60, 60, 60)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(signoutBt, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(usernameLbl))
            .addContainerGap(33, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
}// </editor-fold>                        

private void playBtActionPerformed(java.awt.event.ActionEvent evt) {                                       
    // TODO add your handling code here:
}                                      

private void signoutBtActionPerformed(java.awt.event.ActionEvent evt) {                                          
    // TODO add your handling code here:
    dispose();
    Login l = new Login();
    l.setTitle("Login");
    l.setVisible(true);
}                                         

private void scoreBtActionPerformed(java.awt.event.ActionEvent evt) {                                        
    // TODO add your handling code here:
    dispose();
    HighScore h = new HighScore();
    h.setTitle("HighScore");
    h.setVisible(true);
}                                       

private void signoutBtMouseClicked(java.awt.event.MouseEvent evt) {                                       
    // TODO add your handling code here:
}                                      

private void playBtMouseClicked(java.awt.event.MouseEvent evt) {                                    
    // TODO add your handling code here:
    //buttonSound();
	dispose();
    GameGUI g = new GameGUI();
    g.setTitle("GameGUI");
    g.setVisible(true);
}                                   

private void playBtMousePressed(java.awt.event.MouseEvent evt) {                                    
    // TODO add your handling code here:
}                                   

private void signoutBtMousePressed(java.awt.event.MouseEvent evt) {                                       
    // TODO add your handling code here:
    //buttonSound();
}                                      

private void usernameLblComponentShown(java.awt.event.ComponentEvent evt) {                                           
    // TODO add your handling code here:
    //source code for username
}                                          

private void scoreBtMousePressed(java.awt.event.MouseEvent evt) {                                     
    // TODO add your handling code here:
    //buttonSound();
}                                    

/*private void buttonSound(){
    try{
        File sound = new File("C:\\Users\\USER\\Desktop\\CIS\\Sounds\\kick3.mp3");
        Clip c = AudioSystem.getClip();
        c.open(AudioSystem.getAudioInputStream(sound));
        c.start();
    }catch(Exception e){
    
    }
    
    AudioClip note = new AudioClip(this.getClass().getResource("kick3.mp3").toString());
    note.play();
}*/
/**
 * @param args the command line arguments
 */
public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ClassNotFoundException ex) {
        java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
        java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
        java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
        java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            new Menu().setVisible(true);
        }
    });
}

// Variables declaration - do not modify                     
private javax.swing.JLabel jLabel3;
private javax.swing.JPanel jPanel1;
private javax.swing.JButton playBt;
private javax.swing.JButton scoreBt;
private javax.swing.JButton signoutBt;
public javax.swing.JLabel usernameLbl;
// End of variables declaration   
	
}
